### ISSUE TITLE
proj6+ branch status

### ISSUE THREAD

**Issue by nono303** [swen100/phpng-proj#2]
Hi @swen100,
First, many thx for this php ext (I was searching for it for a long time ^^)
Before making some PR (fixing windows build on config.w32, adding distance function) I would like to know on which branch does I have to work as it's seems that [proj6+](https://github.com/swen100/phpng-proj/tree/proj6+) is in a "strange" state
> This branch is [3 commits ahead](https://github.com/swen100/phpng-proj/compare/master...proj6+), [5 commits behind](https://github.com/swen100/phpng-proj/compare/proj6+...master) master.

Otherwise, my first results are... wonderful ;)

![image](https://user-images.githubusercontent.com/2869665/214333412-e4432351-e6e5-41ad-8eed-fc7607ae38d6.png)

```
>>>>>> testTransform(2056, 4326, [[2628735.83,1177466.63]...{359}]))
------------------------------------------------------------------------
 iter           engine    |  ms      |  res
------------------------------------------------------------------------
x50            NATIVE     | 18.504   | 7.8146916554778  46.747766576805
x50            * PHP-PROJ | 48.01    | 7.8146906996667  46.74777125661
x50            GDAL       | 3344.469 | 7.81469069966669 46.7477712566097
x50            CS2CS      | 3370.474 | 7.8146906997     46.7477712566
x50            PROJ4PHP   | 4913.202 | 7.8146906996667  46.74777125523
------------------------------------------------------------------------
https://epsg.io/transform#s_srs=2056 | 7.8146908        46.7477713
```

```
>>>>>> testDistance(45.832615, 6.865129,44.922525, 6.359967, 4326)
----------------------------------------------
 iter   engine              | ms      | m or °
----------------------------------------------
X1000  nativeHaversineGC | 1.5     | 108738.42
X1000  nativeVincentyGC  | 2       | 108738.42
X1000  * projGeodesic    | 11.002  | 108609.97
X1000  brickGeos         | 19.004  | 1.04
X1000  phpGeosHausdorff  | 66.013  | 1.04
X1000  phpGeos           | 72.514  | 1.04
X1000  MySQL             | 183.537 | 108610.81
X1000  brickMySQL        | 226.545 | 108610.81
X1000  projGeodExe       | 35007.9 | 108609.97
----------------------------------------------
```

**Comment by swen100** [comment]
Hi @nono303 . I have merged the branch into master, so U can work on this one from now.
Additionally I have also taken over your code modifications, as far as possible. Thx a lot!
Please let me know if I've overlooked some things.

**Comment by nono303** [comment]
Hi @swen100,
Many Thx for this work!
All sounds great on master 3.0.3 (you might just tag as it)

Nothing to deal with proj but - based on this – I’m currently trying to wrap gdal and particularly [gdallocationinfo](https://gdal.org/programs/gdallocationinfo.html) to read geotiff (french lidar data).
I’m close to have it working but as I’m not fluent with “messy” (personal consideration ;) gdal C api (as I’m trying to translate [gdallocationinfo.cpp](https://github.com/OSGeo/gdal/blob/master/apps/gdallocationinfo.cpp) in C++) and Geotiff computation, I would be glad to have your advised review **https://github.com/nono303/php-gdal**

++NoNo
